### PR TITLE
Add support for reporting references to discontinued specs

### PR DESCRIPTION
**Pull request by dontcallmedom**

### CODE REVIEW

**Comment by dontcallmedom** [comment]
Dry-running it gives the following output (to be compared with https://github.com/w3c/webref/issues/1096)

Downloading HTML spec fragments data…
- done
Opening crawl results ../webref/ed/index.json and ../webref/tr/index.json…
- done
Running references analysis…
- done
Compiling discontinuedReferences report for HTML Standard…


Would add issues/html-discontinuedreferences.md with
---
Repo: 'https://github.com/whatwg/html'
Tracked: N/A
Title: Normative references to discontinued specs in HTML Standard
---

While crawling [HTML Standard](https://html.spec.whatwg.org/multipage/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [HTTP](https://httpwg.org/specs/rfc7230.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html),[rfc9112](https://httpwg.org/specs/rfc9112.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Navigational-Tracking Mitigations…


Would add issues/nav-tracking-mitigations-discontinuedreferences.md with
---
Repo: 'https://github.com/privacycg/nav-tracking-mitigations'
Tracked: N/A
Title: >-
  Normative references to discontinued specs in Navigational-Tracking
  Mitigations
---

While crawling [Navigational-Tracking Mitigations](https://privacycg.github.io/nav-tracking-mitigations/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7234](https://httpwg.org/specs/rfc7234.html) has been obsoleted by [rfc9111](https://httpwg.org/specs/rfc9111.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Media Feeds…


Would add issues/media-feeds-discontinuedreferences.md with
---
Repo: 'https://github.com/WICG/media-feeds'
Tracked: N/A
Title: Normative references to discontinued specs in Media Feeds
---

While crawling [Media Feeds](https://wicg.github.io/media-feeds/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [rfc7231](https://httpwg.org/specs/rfc7231.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Network Information API…


Would add issues/netinfo-discontinuedreferences.md with
---
Repo: 'https://github.com/WICG/netinfo'
Tracked: N/A
Title: Normative references to discontinued specs in Network Information API
---

While crawling [Network Information API](https://wicg.github.io/netinfo/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7231](https://httpwg.org/specs/rfc7231.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Save Data API…


Would add issues/savedata-discontinuedreferences.md with
---
Repo: 'https://github.com/WICG/savedata'
Tracked: N/A
Title: Normative references to discontinued specs in Save Data API
---

While crawling [Save Data API](https://wicg.github.io/savedata/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7231](https://httpwg.org/specs/rfc7231.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Loading Signed Exchanges…


Would add issues/webpackage-discontinuedreferences.md with
---
Repo: 'https://github.com/WICG/webpackage'
Tracked: N/A
Title: Normative references to discontinued specs in Loading Signed Exchanges
---

While crawling [Loading Signed Exchanges](https://wicg.github.io/webpackage/loading.html), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7230](https://httpwg.org/specs/rfc7230.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html),[rfc9112](https://httpwg.org/specs/rfc9112.html)
* [ ] [RFC7231](https://httpwg.org/specs/rfc7231.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for A Well-Known URL for Changing Passwords…


Would add issues/change-password-url-discontinuedreferences.md with
---
Repo: 'https://github.com/w3c/webappsec-change-password-url'
Tracked: N/A
Title: >-
  Normative references to discontinued specs in A Well-Known URL for Changing
  Passwords
---

While crawling [A Well-Known URL for Changing Passwords](https://w3c.github.io/webappsec-change-password-url/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [HTTP-SEMANTICS](https://httpwg.org/specs/rfc7231.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Clear Site Data…


Would add issues/clear-site-data-discontinuedreferences.md with
---
Repo: 'https://github.com/w3c/webappsec-clear-site-data'
Tracked: N/A
Title: Normative references to discontinued specs in Clear Site Data
---

While crawling [Clear Site Data](https://w3c.github.io/webappsec-clear-site-data/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7230](https://httpwg.org/specs/rfc7230.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html),[rfc9112](https://httpwg.org/specs/rfc9112.html)
* [ ] [RFC7234](https://httpwg.org/specs/rfc7234.html) has been obsoleted by [rfc9111](https://httpwg.org/specs/rfc9111.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Content Security Policy Level 3…


Would add issues/CSP3-discontinuedreferences.md with
---
Repo: 'https://github.com/w3c/webappsec-csp'
Tracked: N/A
Title: Normative references to discontinued specs in Content Security Policy Level 3
---

While crawling [Content Security Policy Level 3](https://w3c.github.io/webappsec-csp/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7231](https://httpwg.org/specs/rfc7231.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for EPUB Reading Systems 3.3…


Would add issues/epub-rs-33-discontinuedreferences.md with
---
Repo: 'https://github.com/w3c/epub-specs'
Tracked: N/A
Title: >-
  [epub-rs-33] Normative references to discontinued specs in EPUB Reading
  Systems 3.3
---

While crawling [EPUB Reading Systems 3.3](https://w3c.github.io/epub-specs/epub33/rs/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [rfc7230](https://httpwg.org/specs/rfc7230.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html),[rfc9112](https://httpwg.org/specs/rfc9112.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Mathematical Markup Language (MathML) Version 4.0…


Would add issues/mathml4-discontinuedreferences.md with
---
Repo: 'https://github.com/w3c/mathml'
Tracked: N/A
Title: >-
  Normative references to discontinued specs in Mathematical Markup Language
  (MathML) Version 4.0
---

While crawling [Mathematical Markup Language (MathML) Version 4.0](https://w3c.github.io/mathml/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [HTTP11](https://httpwg.org/specs/rfc7230.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html),[rfc9112](https://httpwg.org/specs/rfc9112.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Navigation Timing Level 2…


Would add issues/navigation-timing-2-discontinuedreferences.md with
---
Repo: 'https://github.com/w3c/navigation-timing'
Tracked: N/A
Title: Normative references to discontinued specs in Navigation Timing Level 2
---

While crawling [Navigation Timing Level 2](https://w3c.github.io/navigation-timing/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7234](https://httpwg.org/specs/rfc7234.html) has been obsoleted by [rfc9111](https://httpwg.org/specs/rfc9111.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Network Error Logging…


Would add issues/network-error-logging-discontinuedreferences.md with
---
Repo: 'https://github.com/w3c/network-error-logging'
Tracked: N/A
Title: Normative references to discontinued specs in Network Error Logging
---

While crawling [Network Error Logging](https://w3c.github.io/network-error-logging/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7230](https://httpwg.org/specs/rfc7230.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html),[rfc9112](https://httpwg.org/specs/rfc9112.html)
* [ ] [RFC7231](https://httpwg.org/specs/rfc7231.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html)
* [ ] [RFC7232](https://httpwg.org/specs/rfc7232.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html)
* [ ] [RFC7234](https://httpwg.org/specs/rfc7234.html) has been obsoleted by [rfc9111](https://httpwg.org/specs/rfc9111.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Push API…


Would add issues/push-api-discontinuedreferences.md with
---
Repo: 'https://github.com/w3c/push-api'
Tracked: N/A
Title: Normative references to discontinued specs in Push API
---

While crawling [Push API](https://w3c.github.io/push-api/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7231](https://httpwg.org/specs/rfc7231.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Referrer Policy…


Would add issues/referrer-policy-discontinuedreferences.md with
---
Repo: 'https://github.com/w3c/webappsec-referrer-policy'
Tracked: N/A
Title: Normative references to discontinued specs in Referrer Policy
---

While crawling [Referrer Policy](https://w3c.github.io/webappsec-referrer-policy/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7231](https://httpwg.org/specs/rfc7231.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Resource Timing…


Would add issues/resource-timing-discontinuedreferences.md with
---
Repo: 'https://github.com/w3c/resource-timing'
Tracked: N/A
Title: Normative references to discontinued specs in Resource Timing
---

While crawling [Resource Timing](https://w3c.github.io/resource-timing/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7230](https://httpwg.org/specs/rfc7230.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html),[rfc9112](https://httpwg.org/specs/rfc9112.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Server Timing…


Would add issues/server-timing-discontinuedreferences.md with
---
Repo: 'https://github.com/w3c/server-timing'
Tracked: N/A
Title: Normative references to discontinued specs in Server Timing
---

While crawling [Server Timing](https://w3c.github.io/server-timing/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7230](https://httpwg.org/specs/rfc7230.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html),[rfc9112](https://httpwg.org/specs/rfc9112.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Service Workers Nightly…


Would add issues/service-workers-discontinuedreferences.md with
---
Repo: 'https://github.com/w3c/ServiceWorker'
Tracked: N/A
Title: Normative references to discontinued specs in Service Workers Nightly
---

While crawling [Service Workers Nightly](https://w3c.github.io/ServiceWorker/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7230](https://httpwg.org/specs/rfc7230.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html),[rfc9112](https://httpwg.org/specs/rfc9112.html)
* [ ] [RFC7231](https://httpwg.org/specs/rfc7231.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Subresource Integrity…


Would add issues/SRI-discontinuedreferences.md with
---
Repo: 'https://github.com/w3c/webappsec-subresource-integrity'
Tracked: N/A
Title: Normative references to discontinued specs in Subresource Integrity
---

While crawling [Subresource Integrity](https://w3c.github.io/webappsec-subresource-integrity/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7234](https://httpwg.org/specs/rfc7234.html) has been obsoleted by [rfc9111](https://httpwg.org/specs/rfc9111.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Scalable Vector Graphics (SVG) 2…


Would add issues/SVG2-discontinuedreferences.md with
---
Repo: 'https://github.com/w3c/svgwg'
Tracked: N/A
Title: >-
  [SVG2] Normative references to discontinued specs in Scalable Vector Graphics
  (SVG) 2
---

While crawling [Scalable Vector Graphics (SVG) 2](https://svgwg.org/svg2-draft/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [DOM-Level-2-Style](https://www.w3.org/TR/DOM-Level-2-Style/) is discontinued, no known replacement reference

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Upgrade Insecure Requests…


Would add issues/upgrade-insecure-requests-discontinuedreferences.md with
---
Repo: 'https://github.com/w3c/webappsec-upgrade-insecure-requests'
Tracked: N/A
Title: Normative references to discontinued specs in Upgrade Insecure Requests
---

While crawling [Upgrade Insecure Requests](https://w3c.github.io/webappsec-upgrade-insecure-requests/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7231](https://httpwg.org/specs/rfc7231.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for WebDriver…


Would add issues/webdriver2-discontinuedreferences.md with
---
Repo: 'https://github.com/w3c/webdriver'
Tracked: N/A
Title: Normative references to discontinued specs in WebDriver
---

While crawling [WebDriver](https://w3c.github.io/webdriver/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7230](https://httpwg.org/specs/rfc7230.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html),[rfc9112](https://httpwg.org/specs/rfc9112.html)
* [ ] [RFC7231](https://httpwg.org/specs/rfc7231.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html)
* [ ] [RFC7232](https://httpwg.org/specs/rfc7232.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html)
* [ ] [RFC7234](https://httpwg.org/specs/rfc7234.html) has been obsoleted by [rfc9111](https://httpwg.org/specs/rfc9111.html)
* [ ] [RFC7235](https://httpwg.org/specs/rfc7235.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Tracking Preference Expression (DNT)…
Tracking Preference Expression (DNT) is discontinued, skipping

**Comment by dontcallmedom** [comment]
(compared to https://github.com/w3c/webref/issues/1096 the report only focuses on normative references, not links in general; I think it probably is the sufficient result for actually removing the specs from webref unless I'm mistaken, although maybe informative references should be checked as well)

**Comment by dontcallmedom** [comment]
https://github.com/w3c/browser-specs/pull/1143 would likely lead to having more specs identified (e.g. the ones in JSON-LD)

**Comment by tidoust** [comment]
> (compared to [w3c/webref#1096](https://github.com/w3c/webref/issues/1096) the report only focuses on normative references, not links in general; I think it probably is the sufficient result for actually removing the specs from webref unless I'm mistaken, although maybe informative references should be checked as well)

I would also check informative references.

I'm not sure how to define *sufficient result* but the motivation to keep these specs in Webref right now is that removing them would break the generation of some specs. If the outdated RFCs disappear from the list of references, that should mean that the spec no longer targets sections in them. If the outdated RFCs disappear from the list of *normative* references but still exist in the list of *informative* references, the spec may still target sections in them, and thus generation will continue to fail if the spec uses Bikeshed.

**Comment by dontcallmedom** [comment]
I'm not sure I would want to have strudy automatically submit issues for informative references on an ongoing basis, since in general, there may be good reasons to refer informatively to an outdated specs.

We may still want to use it to automate filing issues for this particular transition though (maybe filtering it only to bikesped specs). The list generated for informative references would be:

Downloading HTML spec fragments data…
- done
Opening crawl results ../webref/ed/index.json and ../webref/tr/index.json…
- done
Running references analysis…
- done
Compiling discontinuedReferences report for Navigational-Tracking Mitigations…


Would add issues/nav-tracking-mitigations-discontinuedreferences.md with


---
Repo: 'https://github.com/privacycg/nav-tracking-mitigations'
Tracked: N/A
Title: >-
  Normative references to discontinued specs in Navigational-Tracking
  Mitigations
---

While crawling [Navigational-Tracking Mitigations](https://privacycg.github.io/nav-tracking-mitigations/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [TRACKING-DNT](https://w3c.github.io/dnt/drafts/tracking-dnt.html) is discontinued, no known replacement reference

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Compression Streams…


Would add issues/compression-discontinuedreferences.md with


---
Repo: 'https://github.com/WICG/compression'
Tracked: N/A
Title: Normative references to discontinued specs in Compression Streams
---

While crawling [Compression Streams](https://wicg.github.io/compression/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7230](https://httpwg.org/specs/rfc7230.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html),[rfc9112](https://httpwg.org/specs/rfc9112.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Mitigating Browser Fingerprinting in Web Specifications…


Would add issues/fingerprinting-guidance-discontinuedreferences.md with


---
Repo: 'https://github.com/w3c/fingerprinting-guidance'
Tracked: N/A
Title: >-
  Normative references to discontinued specs in Mitigating Browser
  Fingerprinting in Web Specifications
---

While crawling [Mitigating Browser Fingerprinting in Web Specifications](https://w3c.github.io/fingerprinting-guidance/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7231](https://httpwg.org/specs/rfc7231.html) has been obsoleted by [rfc9110](https://httpwg.org/specs/rfc9110.html)
* [ ] [TRACKING-DNT](https://www.w3.org/TR/tracking-dnt/) is discontinued, no known replacement reference

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---


Compiling discontinuedReferences report for Upgrade Insecure Requests…


Would add issues/upgrade-insecure-requests-discontinuedreferences.md with


---
Repo: 'https://github.com/w3c/webappsec-upgrade-insecure-requests'
Tracked: N/A
Title: Normative references to discontinued specs in Upgrade Insecure Requests
---

While crawling [Upgrade Insecure Requests](https://w3c.github.io/webappsec-upgrade-insecure-requests/), the following normative referenced were detected as pointing to discontinued specifications:
* [ ] [RFC7234](https://httpwg.org/specs/rfc7234.html) has been obsoleted by [rfc9111](https://httpwg.org/specs/rfc9111.html)

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

---

Among those:
* informative references to DNT are probably meant as such
* fingerprinting-guidance is respec, the 3 others bikeshed
* [privacycg/nav-tracking-mitigations](https://github.com/privacycg/nav-tracking-mitigations) is not using auto-sections
* WICG/compression seems to already know the ref is obsolete, although I'm not sure I understand the underlying intent https://github.com/WICG/compression/blob/1d6b643e776bf1972e9a49a84406c218d52ae084/index.bs#L72; it's not using sections in any case
* [w3c/webappsec-upgrade-insecure-requests](https://github.com/w3c/webappsec-upgrade-insecure-requests) is not using sections either

So it looks like none of them would a priori benefit https://github.com/w3c/webref/issues/1096

**Comment by tidoust** [comment]
Overall, that's fine. For the sake of documenting limits of the approach:

> * informative references to DNT are probably meant as such

It would make sense to exclude DNT and other hardcoded specs that we keep crawling precisely so that people can still reference them informatively.

> * [privacycg/nav-tracking-mitigations](https://github.com/privacycg/nav-tracking-mitigations) is not using auto-sections

That's a good example of a spec for which a link-based approach would trap more problems than a reference-based approach. The spec [links to RFC7231](https://github.com/privacycg/nav-tracking-mitigations/blob/main/index.bs#L40-L41) (normatively) but does not have it in its list of references.

A simple link analysis would report the missing reference... and then this analysis would report the discontinued reference. Ideally, we'd manage to combine the reports!

> * [w3c/webappsec-upgrade-insecure-requests](https://github.com/w3c/webappsec-upgrade-insecure-requests) is not using sections either

... but that's because [they turned them into definitions](https://github.com/w3c/webappsec-upgrade-insecure-requests/blob/main/index.bs#L90-L93).

**Review by tidoust — APPROVED** [review]

**Pull request merged**
